version: "2"
services:
    ss-server:
        image: shadowsocks/shadowsocks-libev
        ports:
            - "443:8388/tcp"
            - "443:8388/udp"
        restart: always
        METHOD: xchacha20-ietf-poly1305
        PASSWORD: your_ss_pwd
        # DNS_ADDR: 1.1.1.1
    kcp-server:
        image: xtaci/kcptun:v20200226
        ports:
            - "your_kcp_port:38081/udp"
        restart: always
        depends_on:
            - ss-server
        command: /bin/server -t "ss-server:8388" -l ":38081" -mode fast2 --key your_kcp_key --crypt aes-128
