version: "2"
services:
    ss-server:
        image: spidertifa/ss-server:0.2
        ports:
            - "443:8388/tcp"
            - "443:8388/udp"
        restart: always
        METHOD: aes-256-gcm
        PASSWORD: your_ss_pwd
    kcp-server:
        image: spidertifa/kcp-server:latest
        ports:
            - "your_kcp_port:38081/udp"
        restart: always
        depends_on:
            - ss-server
        command: ./server_linux_amd64 -t "ss-server:8388" -l ":38081" -mode fast2 --key your_kcp_key --crypt aes-128
